apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-app
  #namespace: "{{ .Values.app.namespace }}"
spec:
  selector:
    matchLabels:
      app: data-app
  replicas: 2
  template:
    metadata:
      labels:
        app: data-app
    spec:
      containers:
      - name: data-app
        image: "{{ .Values.app.image }}"
        ports:
        - containerPort: 8080

