apiVersion: v1
kind: Service
metadata:
  name: datapp-service
  # namespace: "{{ .Values.app.namespace }}"
spec:
  selector:
    app: data-app
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080

