name: ci job
on: 
  # push:
  #   branches: 
  #     - master
  workflow_dispatch: 
    inputs:
      message:
         required: true
         description: "Enter any message"
         

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout from SCM
          uses: actions/checkout@v2

        - name: Check if helm is installed
          run: helm version

        - name: Message display
          run: echo "${{ github.event.inputs.message }}"

